[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "teleboss"
version = "5.0.0"
requires-python = ">=3.14.6"
dependencies = [
  "pytelegrambotapi>=4.36.0",
  "packaging>=26.2",
]

[project.scripts]
teleboss = "teleboss.app.entry:main"

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.packages.find]
where = ["src"]
